// exports table
module.exports = (dbinfo, Sequelize) => {
    return dbinfo.define(
      "maitre",
      {
        // field name
        idMaitre: {
          // set date type
          type: Sequelize.DataTypes.INTEGER,
          // set primaryKey
          primaryKey: true,
          // set autoIncrement
          autoIncrement: true
        },
        // field name
        nom: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          // setting allowNull to false will add NOT NULL to the column, which means there will be an error if you don't add info in this column
          allowNull: false
        },
        //field name
        prenom: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          // setting allowNull to false will add NOT NULL to the column, which means there will be an error if you don't add info in this column
          allowNull: false
        },
        adresse: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          allowNull: true
        },
        ville: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          allowNull: true
        },
        code_postal: {
          // set data type with max length
          type: Sequelize.DataTypes.INTEGER,
          allowNull: true
        },
        // field name
        telephone: {
          //set data type with max length
          type: Sequelize.DataTypes.INTEGER,
          allowNull: true
        },
        // field name
        email: {
          //set data type with max length
          type: Sequelize.DataTypes.STRING(60),
          allowNull: false
        },
        mdp: {
          //set data type with max length
          type: Sequelize.DataTypes.TEXT,
          // setting allowNull to false will add NOT NULL to the column, which means an error will be if you add info in this column
          allowNull: false
        },
        nombre_de_chats: {
          //set data type with max length
          type: Sequelize.DataTypes.INTEGER,
          // setting allowNull to false will add NOT NULL to the column, which means an error will be if you add info in this column
          allowNull: true
        },
        statut_disponible: {
          //set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          // setting allowNull to false will add NOT NULL to the column, which means an error will be if you add info in this column
          allowNull: true
        },
        admin: {
          //set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          // setting allowNull to false will add NOT NULL to the column, which means an error will be if you add info in this column
          allowNull: false,
          defaultValue: false
        },
        banni: {
          //set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: false
        }
      },
      {
        /**
         * By default, Sequelize will add the attributes createdAt and updatedAt to your model so you will be able to know when the database entry went into the db and when it was updated last.
         */
        timestamps: true,
        /**
         * Sequelize allow setting underscored option for Model. When true this option will set the field option on all attributes to the underscored version of its name.
         * This also applies to foreign keys generated by associations.
         * */

        // pour concaténer les champs où se trouvent les foreign keys sinon par défaut, on se retrouve avec des champs à rallonge
        underscored: true
      }
    );
};

