// exports table
module.exports = (dbinfo, Sequelize) => {
    return dbinfo.define(
      "nounou",
      {
        // field name
        idNounou: {
          // set date type
          type: Sequelize.DataTypes.INTEGER,
          // set primaryKey
          primaryKey: true,
          // set autoIncrement
          autoIncrement: true
        },
        // field name
        nom: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          allowNull: false
        },
        //field name
        prenom: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          allowNull: false
        },
        adresse: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          allowNull: true
        },
        ville: {
          // set data type with max length
          type: Sequelize.DataTypes.STRING(45),
          allowNull: true
        },
        code_postal: {
          // set data type with max length
          type: Sequelize.DataTypes.INTEGER,
          allowNull: true
        },
        telephone: {
          //set data type with max length
          type: Sequelize.DataTypes.INTEGER,
          allowNull: true
        },
        // field name
        email: {
          //set data type with max length
          type: Sequelize.DataTypes.STRING(60),
          allowNull: false
        },
        // field name
        mdp: {
          //set data type with max length
          type: Sequelize.DataTypes.TEXT,
          allowNull: false
        },
        capacite_d_accueil: {
          //set data type with max length
          type: Sequelize.DataTypes.INTEGER,
          allowNull: true
        },
        a_deja_eu_des_chats: {
          // set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          allowNull: true
        },
        a_deja_eu_des_animaux: {
          // set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          allowNull: true
        },
        non_fumeur: {
          // set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          allowNull: true
        },
        peut_consacrer_n_heure_par_jour: {
          //set data type with max length
          type: Sequelize.DataTypes.INTEGER,
          allowNull: true
        },
        description: {
          //set data type with max length
          type: Sequelize.DataTypes.TEXT,
          allowNull: true
        },
        statut_disponible: {
          //set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          allowNull: true
        },
        
        admin: {
          //set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: false
        },
        banni: {
          //set data type with max length
          type: Sequelize.DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: false
        }
      },
      {
        /**
         * By default, Sequelize will add the attributes createdAt and updatedAt to your model so you will be able to know when the database entry went into the db and when it was updated last.
         */
        timestamps: true,
        /**
         * Sequelize allow setting underscored option for Model. When true this option will set the field option on all attributes to the underscored version of its name.
         * This also applies to foreign keys generated by associations.
         * */

        // pour concaténer les champs où se trouvent les foreign keys sinon par défaut, on se retrouve avec des champs à rallonge
        underscored: true
      }
    );
};

